# Generated by Django 5.0.4 on 2024-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('department', models.TextField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('rollNo', models.IntegerField(max_length=20)),
                ('emailId', models.EmailField(max_length=100)),
                ('collegeId', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
