# Generated by Django 5.0.4 on 2024-04-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.CharField(max_length=20),
        ),
    ]
