# Generated by Django 5.0.4 on 2024-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='collegeId',
            field=models.CharField(max_length=20),
        ),
    ]
